### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by vanyachyzh**
[DEMO LINK](https://vanyachyzh.github.io/layout_dia/)

### CODE REVIEW

**Comment by YegorKorenkov** [comment]
For large screens: it looks that hire us button should be more to the right, logo more to the left
image
image
Also title should be placed more to left

**Comment by YegorKorenkov** [comment]
Should be more places between items. Also text not centered
image

**Comment by YegorKorenkov** [comment]
Wrong card order
image
image

**Comment by YegorKorenkov** [comment]
Check this . also in design a more place between thi logo and cards
image

**Comment by YegorKorenkov** [comment]
Please fix it 
image

**Comment by YegorKorenkov** [comment]
Please check margins (mobile version)
image

**Comment by YegorKorenkov** [comment]
Please check this spacing 
image

**Comment by YegorKorenkov** [comment]
image
Side spacing looks bigger than in design

**Review by VitaliyBondarenko1982 — CHANGES_REQUESTED** [review]
- Check autocomplete for email field

Screenshot from 2023-02-17 13-05-00
for fix try to add this styles for input
```
&:-webkit-autofill {
  border-bottom: 1px solid $button-color;
  -webkit-text-fill-color: #fff !important;
  -webkit-box-shadow: 0 0 0 1000px rgba(0,0,0,0) inset !important;
  box-shadow: 0 0 0 1000px #2c2c2c inset !important;
}
```

- field for message in form must be textarea. After fix it suggest to make custom scrollbar.
https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp

**Review by VitaliyBondarenko1982 — APPROVED** [review]

**Pull request closed without merging**
