### PR TITLE
layout_dia

### PR DESCRIPTION
**Pull request by DmitryVolchokFE**
https://DmitryVolchokFE.github.io/layout_dia/

### CODE REVIEW

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Demo link. Let's discuss it in the chat
image

**Comment by DmitryVolchokFE** [comment]
I would like to ask for your feedback on the structure of html, css. I know that all are beginners (говнокодять =)), so I want to do as well as possible in the initial stages.

**Review by IvanFesenko — CHANGES_REQUESTED** [review]
Remove second scroll
https://github.com/mate-academy/layout_dia/assets/61904995/f19cb1ef-b8a5-4bc8-ace5-85ff51cbb45a

burger menu doesnt works

Fix [autocomplete](https://developer.mozilla.org/en-US/docs/Web/CSS/:autofill) styles 
2023-06-29_15h50_46

All the social icons in the footer should be clickable and open the social networks in a new tab
2023-06-29_15h51_45

**Comment by DmitryVolchokFE** [comment]
image
I fixed everything, the only thing is that during autofill it is impossible to change the font of the add-on itself, as I found out that it is a browser theme that cannot be legally changed.

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
It is necessary to make this menu so that it is on the entire screen in height and it is necessary to prohibit scrolling when it is open
image

**Comment by DmitryVolchokFE** [comment]
Made it full screen, but it looks empty.

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
In this menu, try to show the logo on the left and the cross to close on the right, the button `hire us` is unnecessary here, you can also increase the fonts and indents for the menu items
image

**Comment by DmitryVolchokFE** [comment]
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
It is necessary to ensure that the content does not stretch to the full width on our large screens
Demo
image

Design
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Comment from previous review still isn't fixed

**Comment by DmitryVolchokFE** [comment]
If something is wrong, describe what specifically. thank you

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Previous comments have not been fixed.
The error is that the content stretches to the entire width of the screen, look carefully at the previous screenshots
If you have any questions feel free in fe_chat

**Pull request closed without merging**
