### PR TITLE
solution

### PR DESCRIPTION
**Pull request by ilyaivasyk**
[DEMO LINK](https://ilyaivasyk.github.io/layout_dia/).

### CODE REVIEW

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good job 👍 
Let's improve your page
1. These links should be centered on the page as on the design
image

2. Fix the indent between this element and header as on the design
image

3. The indents between these elements should be are same as on the design
image

4. Need to change the autocomplete styles for the inputs
image

5. Need to remove the scroll when this menu is open
image

**Review by l4st1m0za — CHANGES_REQUESTED** [review]
Previous comments still not changed. May be you forgot to make a deploy!

**Review by l4st1m0za — CHANGES_REQUESTED** [review]
Still no changes, ask in FE chat, if you have any difficulties

**Review by l4st1m0za — CHANGES_REQUESTED** [review]
Redeploy your project, or ask in chat for help to resolve such an issue!
image

**Pull request closed without merging**
