### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Kredinec**
[DEMO LINK](https://Kredinec.github.io/layout_dia/).

### CODE REVIEW

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! 
Screenshot 2024-01-29 at 16 11 02
Check margins here 
Screenshot 2024-01-29 at 16 10 08
The button should be 100% of the container width on mobiles 
Screenshot 2024-01-29 at 16 03 27
Screenshot 2024-01-29 at 16 03 30
Could you please add proper href attributes here?
Screenshot 2024-01-29 at 16 02 55
The form should have clear information on submit

**Review by etojeDenys — CHANGES_REQUESTED** [review]
open the menu on burger click
image

**Comment by Kredinec** [comment]
> open the menu on burger click image

**Comment by Kredinec** [comment]
I have no menu in this landing page. What exactly have i open?

**Comment by IvanFesenko** [comment]
You have menu, how it should looks - up to you
2024-02-01_14h28_02

Also re-open Pull request or this task can't be completed

**Review by IvanFesenko — COMMENTED** [review]
- Placeholder design missmatch
 2024-02-01_14h32_13
- Check design
2024-02-01_14h35_48

**Review by etojeDenys — APPROVED** [review]
good job

**Pull request closed without merging**
