### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by M-Grisha**
[DEMO LINK](https://M-Grisha.github.io/layout_dia/)

### CODE REVIEW

**Comment by TarasHoliuk** [comment]
The logo in the header should be link as well:
image

**Comment by TarasHoliuk** [comment]
The blue line under each nav link moves all content below when appears (on hover)
image

**Comment by TarasHoliuk** [comment]
Add the link to `contact us` section to `hire us` instead of `#hire-us` - it doesn't exist
image

**Comment by TarasHoliuk** [comment]
Add hover effects to images:
image
image

**Comment by TarasHoliuk** [comment]
Add hover effect to all links in the `Contact us` section
Add links to the main pages to the corresponding social media icons
All external links should be open in the new tab (social media, google map)
image

**Comment by TarasHoliuk** [comment]
About form:
- Do not reload the page on submit (`Send` button)
- All fields should be required
- Clear form after submitting

image

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
Well done! But let's improve your app a bit (check comments)

**Review by Bohdan-Maksymiuk — CHANGES_REQUESTED** [review]
check [checklist](https://github.com/mate-academy/layout_dia/blob/master/checklist.md) carefully  - there are a lot of hints

Screenshot 2022-10-21 at 14 23 51

* lets remove default styles on autocomplete 

https://user-images.githubusercontent.com/94289038/197185078-ab6d7f36-ac38-4dc7-a0cc-2fdecdb69339.mov

* lets fix it (there are hints in checklist)
* set favicon


https://user-images.githubusercontent.com/94289038/197185467-27c3f882-ecbe-4b08-903c-305878ce2137.mov

> When a user clicks on Address Google Maps is opened in a new tab (Use target="_blank")

**Comment by M-Grisha** [comment]
@Bohdan-Maksymiuk I fix mistakes

**Review by AlisaVlasova — CHANGES_REQUESTED** [review]
1. use svg for logo and icons
image
2. use placeholder from the mockup and add pattern for validation
image

**Review by marina-tilniak — CHANGES_REQUESTED** [review]
додай favicon

потрібно прибрати цей агресивний валідатор 
image

відправка форми не повинна перезавантажувати сторінку(https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault)

image

**Pull request closed without merging**
