### PR TITLE
DIA (FIXED 08.11.2022)

### PR DESCRIPTION
**Pull request by Igor-Yaremchuk**
[DEMO LINK](https://Igor-Yaremchuk.github.io/layout_dia/)

### CODE REVIEW

**Review by Anastasiia-Svintsova — CHANGES_REQUESTED** [review]
1. Fix this, please
Animation
2. Let's add some effect to hover. You can leave the increase in the neighboring button, but do it when hovering over the text as well
Animation
3. The form shouldn't be submitted if there are empty fields. And remove the styles for autocomplete, it doesn't look good
Animation

**Review by liliia-livandovskaya — CHANGES_REQUESTED** [review]
Great job! Pay attention to the following points:
1. After submitting the form there should not be an error 
Screenshot 2022-12-05 at 16 26 41

2. There should not be a 404 error after clicking on the logo as well 
Screenshot 2022-12-05 at 16 30 34
Screenshot 2022-12-05 at 16 30 46

3. Fix this paragraph on mobile 
Screenshot 2022-12-05 at 16 29 52

**Review by Anastasiia-Svintsova — CHANGES_REQUESTED** [review]
Really good job. 
- Please, fix the form. The page shouldn't reload after submitting. And the user shouldn't see entered data in the search bar

https://user-images.githubusercontent.com/99403198/206852971-dd59e452-7f85-4852-8713-4ade2445e95c.mov

- It's really great that you implemented this theme-switching feature. Let's align the icon to the center
image

**Comment by loralevitska** [comment]
Hello) you have a closed PR. Do you still need a review or have you created a new PR?

**Comment by Igor-Yaremchuk** [comment]
Hello !! I created a ne RP, because a fatal error occurred when i pushed the branch...

**Comment by Igor-Yaremchuk** [comment]
> Hello) you have a closed PR. Do you still need a review or have you created a new PR?

Hello !! I created a ne RP, because a fatal error occurred when i pushed the branch...

**Pull request closed without merging**
