### PR TITLE
Develop dia_landing_page

### PR DESCRIPTION
**Pull request by VSkits**
[DEMO LINK](https://VSkits.github.io/layout_dia/)
https://www.figma.com/file/7qwsWggv9BAxMi2VPhBuPr/Air-(formerly-Dia))?type=design&node-id=22904-672&mode=design&t=K05qzrNkUOz5j9br-0

### CODE REVIEW

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Good start! Keep it up
Fix links, should be uppercase and without `-`
mock
image
now:
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great start! Keep doing! 
Screenshot 2024-03-07 at 15 48 44
Consider fixing links here 
The GoogleMaps and social network links should be opened in the new tabs with proper content (Maps and social networks) 
Screenshot 2024-03-07 at 15 47 33
Check fonts here

**Review by vadiimvooo — CHANGES_REQUESTED** [review]
Good job. Keep going and finish other parts of layout. Here are also a few fixes required:
1. Add transition on hover effect to make it smoothly.
2. You have to remove scroll when burger menu is open.
3. As mentioned previously you have to remove `-` symbol in navigation links
image
image
4. By clicking on the links you should scroll to the apropriate section.
5. Something wrong with textarea font family
image

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Good progress! 
provide anchor links to related sections
image


When you finish with WHOLE page ask for review again

**Review by sTorba24 — CHANGES_REQUESTED** [review]
Keep it up! Do NOT request review before u finish WHOLE page

**Pull request closed without merging**
