### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ZadorozhnyiYevhenii**
[DEMO LINK](https://ZadorozhnyiYevhenii.github.io/layout_dia/)

### CODE REVIEW

**Review by vlad-demchuk — CHANGES_REQUESTED** [review]
1. add indents under the navigation according to the mockup
image
2. all external links should be opened in a new tab
image
3. message input shouldn't be a type of email
image
4. change autocomplete styles
image

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
1. Still not fixed from the previous review
image

2. Need to fix block contact us
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! Almost done: 
Screenshot 2023-07-28 at 14 01 18
Screenshot 2023-07-28 at 14 01 24
Consider adding hovers to the links in the footer

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Awesome work! Almost done! Consider fixing hover styles for footer links from the previous review

**Pull request closed without merging**
