### PR TITLE
dia

### PR DESCRIPTION
**Pull request by mykolahuryn**
[DEMO LINK](https://mykolahuryn.github.io/layout_dia/).

### CODE REVIEW

**Comment by TarasHoliuk** [comment]
The [checklist](https://github.com/mate-academy/layout_dia#checklist-for-preparing-a-portfolio-project-for-hr-review) points: 7, 9, 11, 14, 20

1. Click on the logo shouldn't lead to a 404 page:
image

2. Color of the cross icon should be white (now it's badly visible)

3. Check the background color for sections:
- mockup:
image
- app:
image

**Review by TarasHoliuk — CHANGES_REQUESTED** [review]
GJ :+1: 
But a few things should be fixed (check comments)

**Review by polosanya — CHANGES_REQUESTED** [review]
Almost done! Please compare your page with the design. Pay attention to the tablet and mobile versions too
1. Background color still doesn't match the design
image
image
2. After autocomplete the form, change the [default styles](http://joxi.ru/EA4xgG8HXwL4lA). Read more about [changing autocomplete styles](https://css-tricks.com/snippets/css/change-autocomplete-styles-webkit-browsers/)
image
3. Mobile version doesn't match the design
image
image
image
image

**Review by qoa11a — CHANGES_REQUESTED** [review]
image
The image overlaps the button.

**Review by polosanya — APPROVED** [review]
Well done!

**Pull request closed without merging**
