### PR TITLE
DIA

### PR DESCRIPTION
**Pull request by timohahaaa**
https://timohahaaa.github.io/layout_dia/

### CODE REVIEW

**Review by etojeDenys — CHANGES_REQUESTED** [review]
.

**Review by volodymyr-soltys97 — CHANGES_REQUESTED** [review]
Good job 👍 
Let's improve your page
1. Add hover effects for all clickable elements on the page

2. Need to fix the indent between these elements as on the design
image

3. The same
image

4. Add a transition when this menu appears on the page also need to remove the scroll when this menu is open
image

**Review by anastasiiavorobiova — CHANGES_REQUESTED** [review]
Great work! Consider fixing validation errors: 
Screenshot 2023-12-26 at 15 42 16
Screenshot 2023-12-26 at 15 42 24
Screenshot 2023-12-26 at 15 42 28
Screenshot 2023-12-26 at 15 42 37
Screenshot 2023-12-26 at 15 43 00
Screenshot 2023-12-26 at 15 43 05
Screenshot 2023-12-26 at 15 43 14
These links should be opened in the new tab with proper social media
Screenshot 2023-12-26 at 15 37 40
The button should have the full width on the mobile

**Review by anastasiia-tilikina — CHANGES_REQUESTED** [review]
Almost done!

Add scroll behaviour: smooth for your page
Form submitting shouldn't reload page. It should only reset fields

**Review by anastasiia-tilikina — APPROVED** [review]
Well done!

**Pull request closed without merging**
